name: Run the script

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Enter the domain name"
        required: true
        default: "davidmaximous.me"

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      DOMAIN: ${{ github.event.inputs.domain }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Make shell script executable
        run: chmod +x entry.sh

      - name: Run script
        run: ./entry.sh "$DOMAIN"

      - name: Zip output folder
        run: |
          DOMAIN=${{ github.event.inputs.domain }}
          mkdir -p artifacts
          zip -r "artifacts/${DOMAIN}.zip" output/

      - name: Send ZIP to Discord
        run: |
          DOMAIN=${{ github.event.inputs.domain }}
          FILE="artifacts/${DOMAIN}.zip"
          if [ -f "$FILE" ]; then
            curl -F "file=@$FILE" \
                 -F "payload_json={\"content\": \"📦 Output ZIP for $DOMAIN\"}" \
                 ${{ secrets.DISCORD_WEBHOOK }}
          else
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"❌ ZIP file not found for $DOMAIN\"}" \
                 ${{ secrets.DISCORD_WEBHOOK }}
          fi
