name: Run the script

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Enter the domain name"
        required: true
        default: "davidmaximous.me"

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      DOMAIN: ${{ github.event.inputs.domain }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Make shell script executable
        run: chmod +x entry.sh

      - name: Check if DISCORD_WEBHOOK secret is available
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "❌ Webhook secret is NOT accessible in this run!"
          else
            echo "✅ Webhook secret is present."
          fi

      - name: Run script
        run: ./entry.sh "$DOMAIN"

      - name: Zip output folder
        run: |
          DOMAIN=${{ github.event.inputs.domain }}
          mkdir -p artifacts
          zip -r "artifacts/${DOMAIN}.zip" output/

      - name: Upload ZIP to Discord (hardcoded webhook)
        run: |
          DOMAIN=${{ github.event.inputs.domain }}
          FILE="artifacts/${DOMAIN}.zip"
          WEBHOOK_URL="https://discord.com/api/webhooks/1400939131093123113/39JBCU57iA9JycYBkgbb-DNPhbKp8iQpzhz6J94lTgSMAmAmtpb7Jz6QFK3KKRy6N7K8"
          
          if [ -f "$FILE" ]; then
            echo "📤 Sending ZIP to Discord..."
            curl -F "file=@$FILE" \
                 -F "payload_json={\"content\": \"📦 Output ZIP for $DOMAIN\"}" \
                 "$WEBHOOK_URL"
          else
            echo "❌ ZIP file not found: $FILE"
          fi


#      - name: Send ZIP to Discord
#        run: |
#          DOMAIN=${{ github.event.inputs.domain }}
#          FILE="artifacts/${DOMAIN}.zip"
#          if [ -f "$FILE" ]; then
#            curl -F "file=@$FILE" \
#                 -F "payload_json={\"content\": \"📦 Output ZIP for $DOMAIN\"}" \
#                 ${{ secrets.DISCORD_WEBHOOK }}
#          else
#            curl -H "Content-Type: application/json" \
#                 -X POST \
#                 -d "{\"content\": \"❌ ZIP file not found for $DOMAIN\"}" \
#                 ${{ secrets.DISCORD_WEBHOOK }}
#          fi
